"""Generate the human indexes from the plan/ item tree.

--write regenerates. --check fails when the committed output differs from a
fresh render, matching regenerate-weights.py --check and
generate-vectors.py --check. The item files are the only input, so the index can
never become a second source of truth.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.plan.migrate import read_day_records  # noqa: E402
from tools.plan.model import STATUS_GLYPHS, load_milestones, load_questions  # noqa: E402

TITLE_WIDTH = 80
# Some milestone rows carry multi-clause spec citations and exclusion prose (e.g.
# F9's three-bullet Spec column), not the short "10 §6" the table shape assumes.
# The index promises "no prose in cells" as strongly as it promises a narrow
# title, so Spec and Depends are truncated on the same principle.
SPEC_WIDTH = 55
DEPENDS_WIDTH = 30
# Narrower than the milestone widths: a question row also carries a link
# target twice the width of a milestone's ("questions/SQ-NNNN.md" vs
# "milestones/F8.md"), so the same TITLE_WIDTH/SPEC_WIDTH would push real
# rows past 200 characters (measured against the real corpus, 2026-08-12).
QUESTION_TITLE_WIDTH = 60
QUESTION_SPEC_WIDTH = 45
RAISED_WIDTH = 25
# Unlike a milestone/question title, a decision heading is already bounded
# at emit time (`tools.plan.migrate.RECORD_HEADING_WIDTH` = 57, fix round 2)
# — the record's own `## ` heading is never longer than that, so this
# renderer needs no further truncation of its own; a decision-specific
# width constant here would just be a second, driftable copy of that limit.
AUTHORIZED_BY_WIDTH = 30
BANNER = "<!-- Generated by tools/plan/render.py. Do not edit by hand. -->"

_ANCHOR_STRIP_RE = re.compile(r"[^\w\s-]", re.UNICODE)
_ANCHOR_SPACE_RE = re.compile(r"\s+")


def escape_cell(text: str) -> str:
    """GFM splits a cell on a bare pipe, even inside backticks.

    Also breaks up a `](` adjacency the source prose may itself carry (a
    spec-question row commonly quotes a citation like
    "[02](docs/architecture/02-integration-contract.md)"). Left intact inside
    a truncated, escaped table cell, that reads as a real Markdown link to
    check-doc-links.py, resolved against this generated index's own
    directory rather than the source's — and it is frequently truncated
    mid-target besides. A single space is enough to stop it parsing as a
    link while leaving the prose readable; the item file's own body still
    carries the citation as a real, working link.
    """
    return text.replace("|", "\\|").replace("](", "] (")


def _truncate(text: str, width: int = TITLE_WIDTH) -> str:
    if len(text) <= width:
        return text
    return text[: width - 1].rstrip() + "…"


def render_milestones(items) -> str:
    lines = [BANNER, "", "# Milestones", ""]
    for track in sorted({item.track for item in items}):
        lines += [f"## Track {track}", ""]
        lines += ["| ID | Milestone | Spec | Depends | Status |", "|---|---|---|---|---|"]
        for item in sorted(
            (i for i in items if i.track == track), key=lambda i: (len(i.id), i.id)
        ):
            # The two literals are kept apart so this source line is not itself a
            # Markdown link. check-doc-links.py matches link syntax anywhere in a
            # file, fenced code included, and would try to resolve the f-string.
            target = f"milestones/{item.id}.md"
            link = f"[{escape_cell(_truncate(item.title))}]" f"({target})"
            spec = escape_cell(_truncate("; ".join(item.spec), SPEC_WIDTH)) or "—"
            depends = escape_cell(_truncate(", ".join(item.depends), DEPENDS_WIDTH)) or "—"
            lines.append(
                f"| {item.id} | {link} | {spec} | {depends} | {STATUS_GLYPHS[item.status]} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def render_questions(items) -> str:
    lines = [BANNER, "", "# Spec questions", ""]
    for status in ("open", "resolved"):
        group = [item for item in items if item.status == status]
        if not group:
            continue
        lines += [f"## {status.capitalize()}", ""]
        lines += ["| ID | Question | Spec ref | Raised | Batch |", "|---|---|---|---|---|"]
        for item in sorted(group, key=lambda i: (len(i.id), i.id)):
            # Kept apart for the same reason render_milestones keeps its link
            # literals apart: check-doc-links.py resolves link syntax anywhere
            # in the file, and an f-string link would be resolved as source.
            target = f"questions/{item.id}.md"
            link = f"[{escape_cell(_truncate(item.title, QUESTION_TITLE_WIDTH))}]" f"({target})"
            spec_ref = escape_cell(_truncate(item.spec_ref, QUESTION_SPEC_WIDTH)) or "—"
            raised = escape_cell(_truncate(item.raised, RAISED_WIDTH)) or "—"
            batch = escape_cell(item.batch) or "—"
            lines.append(f"| {item.id} | {link} | {spec_ref} | {raised} | {batch} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def _anchor(heading: str) -> str:
    """Approximate GitHub's own heading-anchor slug: lowercase, drop
    punctuation (keeping word characters, whitespace and hyphens), collapse
    whitespace to a single hyphen.

    Built from the **whole** heading passed in. Fix round 1 built this from
    a 30-character prefix of the heading and 259 of 262 anchors matched no
    real heading, because GitHub's slug is a function of the entire heading.
    Fix round 2 tried the opposite (the full, un-truncated heading) and that
    broke differently — the heading itself could be 1,450 characters, an
    unusable `## ` line and an unusable `DECISIONS.md` row alike. The actual
    fix is upstream of this function: `tools.plan.migrate._bound_heading`
    now bounds every record's heading at emit time (57 characters, derived
    from this exact row's 200-character ceiling — see that function's own
    docstring for the arithmetic), so by the time a heading reaches this
    renderer it is already short and this need only slug it whole.
    `tools/ci/check-doc-links.py` never verifies the fragment half of a link
    anyway — it parses the URL, keeps only the path, and explicitly skips a
    fragment-only target — so this is for a human reader landing on the
    right heading, not a gate.
    """
    slug = _ANCHOR_STRIP_RE.sub("", heading.lower()).strip()
    return _ANCHOR_SPACE_RE.sub("-", slug)


def _disambiguate_anchor(base: str, counts: dict[str, int]) -> str:
    """GitHub's own repeat-heading rule: the first occurrence of a slug in a
    file keeps it bare; the second gets `-1`, the third `-2`, and so on, in
    document order. `counts` is mutated in place, keyed by file (the caller
    passes one dict per target file) and by base slug within it — three
    headings repeat within the real `2026-08-06` decisions day file, so this
    is exercised by the live corpus, not only by a fixture.
    """
    seen = counts.get(base, 0)
    counts[base] = seen + 1
    return base if seen == 0 else f"{base}-{seen}"


def _decision_label(heading: str) -> str:
    """`escape_cell` plus one more neutralization this renderer alone needs.

    `[VERIFY]`-style bracket notation (13 §1's own convention) is common in
    decision prose, and a bare `[`/`]` *inside* a link label breaks
    `check-doc-links.py`'s `\\[[^\\]]*\\]\\(...\\)` regex — the inner `]`
    ends the character class early, so the whole label+target stops
    matching as a link at all. Measured against the real corpus (fix round
    1, finding 1's own verification pass): 3 of 262 rows hit exactly this,
    dropping the anchor-match count from 262/262 to 259/262 even though
    every anchor computed correctly. `escape_cell` already applies this
    same kind of workaround for `|` and `](`; brackets get one too, but
    only here — `render_milestones`/`render_questions` share `escape_cell`
    and regenerate `plan/MILESTONES.md`/`plan/QUESTIONS.md`, which this
    task must not touch (Task 4/6 own those indexes), so the fix is local
    to the decisions label rather than added to the shared function.
    """
    return heading.replace("[", "").replace("]", "")


def render_decisions(root: Path) -> tuple[str, list[str]]:
    """Only `decisions` is indexed among the four day-record kinds: it is
    the one kind cited from elsewhere by topic (R-1's "record it in the
    Decision log"), where `log`/`audits`/`changes` are read by date instead.

    Returns (rendered text, errors) rather than raising, matching how
    `main` already collects `load_milestones`/`load_questions` errors
    before deciding whether to write anything.
    """
    records, errors = read_day_records(root, "decisions")
    if errors:
        return "", errors
    lines = [BANNER, "", "# Decisions", ""]
    lines += ["| Date | Amendment | Authorized by |", "|---|---|---|"]
    # Keyed by the day-file path, so a repeated slug is disambiguated within
    # its own file — the same scope `_parse_day_file` reads headings in and
    # the same scope GitHub itself disambiguates within.
    anchor_counts: dict[Path, dict[str, int]] = {}
    for record in records:  # read_day_records is already chronological, then source order
        year, month, _ = record.date.split("-")
        target = f"decisions/{year}/{month}/{record.date}.md"
        base_anchor = _anchor(record.heading)
        anchor = _disambiguate_anchor(base_anchor, anchor_counts.setdefault(record.path, {}))
        # Kept apart for the same reason render_milestones/render_questions
        # keep their link literals apart: check-doc-links.py resolves link
        # syntax anywhere in the file, and an f-string link would be
        # resolved as source.
        # `record.heading` is already bounded at emit time (fix round 2), so
        # no further truncation happens here — only the two neutralizations
        # this renderer's own link syntax needs.
        label = escape_cell(_decision_label(record.heading))
        link = f"[{label}]" f"({target}#{anchor})"
        authorized_by = escape_cell(_truncate(record.fields.get("authorized_by", ""), AUTHORIZED_BY_WIDTH)) or "—"
        lines.append(f"| {record.date} | {link} | {authorized_by} |")
    lines.append("")
    return "\n".join(lines) + "\n", []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path("."))
    args = parser.parse_args(argv)

    milestones, milestone_errors = load_milestones(args.root)
    questions, question_errors = load_questions(args.root)
    decisions_text, decisions_errors = render_decisions(args.root)
    errors = milestone_errors + question_errors + decisions_errors
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    outputs = {
        args.root / "plan" / "MILESTONES.md": render_milestones(milestones),
        args.root / "plan" / "QUESTIONS.md": render_questions(questions),
        args.root / "plan" / "DECISIONS.md": decisions_text,
    }

    failed = False
    for path, expected in outputs.items():
        if args.write:
            path.write_text(expected, encoding="utf-8")
            print(f"wrote {path}")
            continue
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            print(f"{path}: differs from a fresh render; run tools/plan/render.py --write", file=sys.stderr)
            failed = True
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
