"""Generate the human indexes from the plan/ item tree.

--write regenerates. --check fails when the committed output differs from a
fresh render, matching regenerate-weights.py --check and
generate-vectors.py --check. The item files are the only input, so the index can
never become a second source of truth.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from tools.plan.model import STATUS_GLYPHS, load_milestones, load_questions  # noqa: E402

TITLE_WIDTH = 80
# Some milestone rows carry multi-clause spec citations and exclusion prose (e.g.
# F9's three-bullet Spec column), not the short "10 §6" the table shape assumes.
# The index promises "no prose in cells" as strongly as it promises a narrow
# title, so Spec and Depends are truncated on the same principle.
SPEC_WIDTH = 55
DEPENDS_WIDTH = 30
# Narrower than the milestone widths: a question row also carries a link
# target twice the width of a milestone's ("questions/SQ-NNNN.md" vs
# "milestones/F8.md"), so the same TITLE_WIDTH/SPEC_WIDTH would push real
# rows past 200 characters (measured against the real corpus, 2026-08-12).
QUESTION_TITLE_WIDTH = 60
QUESTION_SPEC_WIDTH = 45
RAISED_WIDTH = 25
BANNER = "<!-- Generated by tools/plan/render.py. Do not edit by hand. -->"


def escape_cell(text: str) -> str:
    """GFM splits a cell on a bare pipe, even inside backticks.

    Also breaks up a `](` adjacency the source prose may itself carry (a
    spec-question row commonly quotes a citation like
    "[02](docs/architecture/02-integration-contract.md)"). Left intact inside
    a truncated, escaped table cell, that reads as a real Markdown link to
    check-doc-links.py, resolved against this generated index's own
    directory rather than the source's — and it is frequently truncated
    mid-target besides. A single space is enough to stop it parsing as a
    link while leaving the prose readable; the item file's own body still
    carries the citation as a real, working link.
    """
    return text.replace("|", "\\|").replace("](", "] (")


def _truncate(text: str, width: int = TITLE_WIDTH) -> str:
    if len(text) <= width:
        return text
    return text[: width - 1].rstrip() + "…"


def render_milestones(items) -> str:
    lines = [BANNER, "", "# Milestones", ""]
    for track in sorted({item.track for item in items}):
        lines += [f"## Track {track}", ""]
        lines += ["| ID | Milestone | Spec | Depends | Status |", "|---|---|---|---|---|"]
        for item in sorted(
            (i for i in items if i.track == track), key=lambda i: (len(i.id), i.id)
        ):
            # The two literals are kept apart so this source line is not itself a
            # Markdown link. check-doc-links.py matches link syntax anywhere in a
            # file, fenced code included, and would try to resolve the f-string.
            target = f"milestones/{item.id}.md"
            link = f"[{escape_cell(_truncate(item.title))}]" f"({target})"
            spec = escape_cell(_truncate("; ".join(item.spec), SPEC_WIDTH)) or "—"
            depends = escape_cell(_truncate(", ".join(item.depends), DEPENDS_WIDTH)) or "—"
            lines.append(
                f"| {item.id} | {link} | {spec} | {depends} | {STATUS_GLYPHS[item.status]} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def render_questions(items) -> str:
    lines = [BANNER, "", "# Spec questions", ""]
    for status in ("open", "resolved"):
        group = [item for item in items if item.status == status]
        if not group:
            continue
        lines += [f"## {status.capitalize()}", ""]
        lines += ["| ID | Question | Spec ref | Raised | Batch |", "|---|---|---|---|---|"]
        for item in sorted(group, key=lambda i: (len(i.id), i.id)):
            # Kept apart for the same reason render_milestones keeps its link
            # literals apart: check-doc-links.py resolves link syntax anywhere
            # in the file, and an f-string link would be resolved as source.
            target = f"questions/{item.id}.md"
            link = f"[{escape_cell(_truncate(item.title, QUESTION_TITLE_WIDTH))}]" f"({target})"
            spec_ref = escape_cell(_truncate(item.spec_ref, QUESTION_SPEC_WIDTH)) or "—"
            raised = escape_cell(_truncate(item.raised, RAISED_WIDTH)) or "—"
            batch = escape_cell(item.batch) or "—"
            lines.append(f"| {item.id} | {link} | {spec_ref} | {raised} | {batch} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=Path("."))
    args = parser.parse_args(argv)

    milestones, milestone_errors = load_milestones(args.root)
    questions, question_errors = load_questions(args.root)
    errors = milestone_errors + question_errors
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    outputs = {
        args.root / "plan" / "MILESTONES.md": render_milestones(milestones),
        args.root / "plan" / "QUESTIONS.md": render_questions(questions),
    }

    failed = False
    for path, expected in outputs.items():
        if args.write:
            path.write_text(expected, encoding="utf-8")
            print(f"wrote {path}")
            continue
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual != expected:
            print(f"{path}: differs from a fresh render; run tools/plan/render.py --write", file=sys.stderr)
            failed = True
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
