
//! Autogenerated weights for `pallet_oracle`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-07-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_oracle
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_oracle.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_oracle`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_oracle::WeightInfo for WeightInfo<T> {
	/// Storage: `Oracle::Reporters` (r:65 w:1)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:0)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::CounterForReporters` (r:1 w:1)
	/// Proof: `Oracle::CounterForReporters` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn register_reporter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197769`
		//  Estimated: `356514`
		// Minimum execution time: 1_298_562_000 picoseconds.
		Weight::from_parts(1_311_261_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(345))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:1)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:0)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::CounterForReporters` (r:1 w:1)
	/// Proof: `Oracle::CounterForReporters` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn deregister_reporter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197843`
		//  Estimated: `356514`
		// Minimum execution time: 1_289_321_000 picoseconds.
		Weight::from_parts(1_308_012_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(345))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Welfare::MetricSpecs` (r:1 w:0)
	/// Proof: `Welfare::MetricSpecs` (`max_values`: None, `max_size`: Some(3379), added: 5854, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:128 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	fn report() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196782`
		//  Estimated: `353758`
		// Minimum execution time: 1_320_431_000 picoseconds.
		Weight::from_parts(1_334_972_000, 0)
			.saturating_add(Weight::from_parts(0, 353758))
			.saturating_add(T::DbWeight::get().reads(346))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	fn challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197843`
		//  Estimated: `356514`
		// Minimum execution time: 1_297_112_000 picoseconds.
		Weight::from_parts(1_306_131_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(344))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:128 w:1)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:1)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25297), added: 25792, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:6 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[8, 262144]`.
	fn recompute_proof(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209370`
		//  Estimated: `356514`
		// Minimum execution time: 1_417_322_000 picoseconds.
		Weight::from_parts(1_417_933_264, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			// Standard Error: 15
			.saturating_add(Weight::from_parts(1_427, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(354))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:1)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:0)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:1)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::CounterForWatchtowers` (r:1 w:1)
	/// Proof: `Oracle::CounterForWatchtowers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn register_watchtower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188389`
		//  Estimated: `356514`
		// Minimum execution time: 1_250_812_000 picoseconds.
		Weight::from_parts(1_266_691_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(345))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:1)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25297), added: 25792, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:6 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn ack_observed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209373`
		//  Estimated: `356514`
		// Minimum execution time: 1_402_312_000 picoseconds.
		Weight::from_parts(1_438_901_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(355))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:10)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:119 w:10)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:1)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25297), added: 25792, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:6 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn crank_round_close(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209441`
		//  Estimated: `356514`
		// Minimum execution time: 1_393_791_000 picoseconds.
		Weight::from_parts(1_397_356_900, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			// Standard Error: 136_094
			.saturating_add(Weight::from_parts(19_662_676, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(355))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:0)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:1)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25297), added: 25792, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:6 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn crank_reserve_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `209446`
		//  Estimated: `356514`
		// Minimum execution time: 1_348_761_000 picoseconds.
		Weight::from_parts(1_357_011_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(355))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:128 w:1)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:1)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	fn adjudicate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197807`
		//  Estimated: `356514`
		// Minimum execution time: 1_315_082_000 picoseconds.
		Weight::from_parts(1_324_252_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(343))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
