
//! Autogenerated weights for `pallet_conditional_ledger`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_conditional_ledger
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_conditional_ledger.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_conditional_ledger`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_conditional_ledger::WeightInfo for WeightInfo<T> {
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `InflowCaps::CumulativeDeposits` (r:1 w:0)
	/// Proof: `InflowCaps::CumulativeDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn split() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2759`
		//  Estimated: `36928`
		// Minimum execution time: 206_730_000 picoseconds.
		Weight::from_parts(214_830_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(42))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn merge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2511`
		//  Estimated: `36928`
		// Minimum execution time: 204_090_000 picoseconds.
		Weight::from_parts(210_480_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `InflowCaps::CumulativeDeposits` (r:1 w:0)
	/// Proof: `InflowCaps::CumulativeDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn split_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3202`
		//  Estimated: `36928`
		// Minimum execution time: 195_930_000 picoseconds.
		Weight::from_parts(200_740_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(42))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn merge_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2661`
		//  Estimated: `36928`
		// Minimum execution time: 187_320_000 picoseconds.
		Weight::from_parts(192_670_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `InflowCaps::CumulativeDeposits` (r:1 w:0)
	/// Proof: `InflowCaps::CumulativeDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn split_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3202`
		//  Estimated: `36928`
		// Minimum execution time: 194_790_000 picoseconds.
		Weight::from_parts(201_850_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(42))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn merge_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2659`
		//  Estimated: `36928`
		// Minimum execution time: 185_060_000 picoseconds.
		Weight::from_parts(189_480_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:2 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:28 w:28)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2779`
		//  Estimated: `72866`
		// Minimum execution time: 288_210_000 picoseconds.
		Weight::from_parts(297_019_000, 0)
			.saturating_add(Weight::from_parts(0, 72866))
			.saturating_add(T::DbWeight::get().reads(55))
			.saturating_add(T::DbWeight::get().writes(49))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `InflowCaps::CumulativeDeposits` (r:1 w:0)
	/// Proof: `InflowCaps::CumulativeDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn split_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2638`
		//  Estimated: `11418`
		// Minimum execution time: 120_810_000 picoseconds.
		Weight::from_parts(125_620_000, 0)
			.saturating_add(Weight::from_parts(0, 11418))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn merge_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2374`
		//  Estimated: `7404`
		// Minimum execution time: 118_180_000 picoseconds.
		Weight::from_parts(122_510_000, 0)
			.saturating_add(Weight::from_parts(0, 7404))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn resolve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `464`
		//  Estimated: `36256`
		// Minimum execution time: 56_220_000 picoseconds.
		Weight::from_parts(58_450_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(15))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn void() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `464`
		//  Estimated: `36256`
		// Minimum execution time: 57_780_000 picoseconds.
		Weight::from_parts(60_550_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn settle_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `465`
		//  Estimated: `36256`
		// Minimum execution time: 57_710_000 picoseconds.
		Weight::from_parts(60_530_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn settle_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `465`
		//  Estimated: `36256`
		// Minimum execution time: 56_360_000 picoseconds.
		Weight::from_parts(59_210_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(15))
	}
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::BaselineTerminalAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn settle_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `337`
		//  Estimated: `6028`
		// Minimum execution time: 21_970_000 picoseconds.
		Weight::from_parts(23_180_000, 0)
			.saturating_add(Weight::from_parts(0, 6028))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn redeem() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2554`
		//  Estimated: `36928`
		// Minimum execution time: 205_320_000 picoseconds.
		Weight::from_parts(211_290_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn redeem_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2704`
		//  Estimated: `36928`
		// Minimum execution time: 214_310_000 picoseconds.
		Weight::from_parts(221_640_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn redeem_scalar_pair() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2704`
		//  Estimated: `36928`
		// Minimum execution time: 213_880_000 picoseconds.
		Weight::from_parts(220_880_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn redeem_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2703`
		//  Estimated: `36928`
		// Minimum execution time: 212_110_000 picoseconds.
		Weight::from_parts(220_770_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn redeem_void() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2545`
		//  Estimated: `36928`
		// Minimum execution time: 206_790_000 picoseconds.
		Weight::from_parts(214_500_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(37))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn redeem_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2394`
		//  Estimated: `7404`
		// Minimum execution time: 118_670_000 picoseconds.
		Weight::from_parts(124_370_000, 0)
			.saturating_add(Weight::from_parts(0, 7404))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:1 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:1 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	fn redeem_baseline_pair() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2394`
		//  Estimated: `7404`
		// Minimum execution time: 118_610_000 picoseconds.
		Weight::from_parts(123_970_000, 0)
			.saturating_add(Weight::from_parts(0, 7404))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:1 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:9 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:114 w:100)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:100 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:100 w:100)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:104 w:104)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	fn sweep_dust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41563`
		//  Estimated: `334518`
		// Minimum execution time: 5_563_729_000 picoseconds.
		Weight::from_parts(5_722_959_000, 0)
			.saturating_add(Weight::from_parts(0, 334518))
			.saturating_add(T::DbWeight::get().reads(535))
			.saturating_add(T::DbWeight::get().writes(311))
	}
	/// Storage: `ConditionalLedger::BaselineTerminalAt` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineTerminalAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:9 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:102 w:100)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Market::MarketProtocolAccounts` (r:100 w:0)
	/// Proof: `Market::MarketProtocolAccounts` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:100 w:100)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:104 w:104)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	fn sweep_dust_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41301`
		//  Estimated: `334518`
		// Minimum execution time: 5_155_028_000 picoseconds.
		Weight::from_parts(5_257_359_000, 0)
			.saturating_add(Weight::from_parts(0, 334518))
			.saturating_add(T::DbWeight::get().reads(523))
			.saturating_add(T::DbWeight::get().writes(311))
	}
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:0 w:1)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_split_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_820_000 picoseconds.
		Weight::from_parts(4_200_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:1)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::FreezeRenewed` (r:0 w:1)
	/// Proof: `ConditionalLedger::FreezeRenewed` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_frozen() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `1489`
		// Minimum execution time: 5_540_000 picoseconds.
		Weight::from_parts(6_040_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
