
//! Autogenerated weights for `pallet_oracle`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_oracle
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_oracle.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_oracle`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_oracle::WeightInfo for WeightInfo<T> {
	/// Storage: `Constitution::Params` (r:12 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Reporters` (r:65 w:1)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:0)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:129 w:0)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::CounterForReporters` (r:1 w:1)
	/// Proof: `Oracle::CounterForReporters` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn register_reporter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `206135`
		//  Estimated: `356514`
		// Minimum execution time: 1_558_079_000 picoseconds.
		Weight::from_parts(1_619_359_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(486))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:1)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:0)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:129 w:0)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::CounterForReporters` (r:1 w:1)
	/// Proof: `Oracle::CounterForReporters` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn deregister_reporter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `203707`
		//  Estimated: `356514`
		// Minimum execution time: 1_516_779_000 picoseconds.
		Weight::from_parts(1_612_219_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(474))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Welfare::MetricSpecs` (r:1 w:0)
	/// Proof: `Welfare::MetricSpecs` (`max_values`: None, `max_size`: Some(3379), added: 5854, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::CohortSchedules` (r:2 w:0)
	/// Proof: `Epoch::CohortSchedules` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:12 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:128 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:128 w:1)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	fn report() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `205173`
		//  Estimated: `353758`
		// Minimum execution time: 1_625_029_000 picoseconds.
		Weight::from_parts(1_678_429_000, 0)
			.saturating_add(Weight::from_parts(0, 353758))
			.saturating_add(T::DbWeight::get().reads(488))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:129 w:0)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	fn challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `203707`
		//  Estimated: `356514`
		// Minimum execution time: 1_567_169_000 picoseconds.
		Weight::from_parts(1_600_719_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(473))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:129 w:1)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:128 w:1)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:1)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:6 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[8, 262144]`.
	fn recompute_proof(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215737`
		//  Estimated: `356514`
		// Minimum execution time: 1_696_059_000 picoseconds.
		Weight::from_parts(1_718_521_406, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			// Standard Error: 5
			.saturating_add(Weight::from_parts(1_237, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(483))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `Constitution::Params` (r:12 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:1)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:0)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:129 w:0)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:0)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:1)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::CounterForWatchtowers` (r:1 w:1)
	/// Proof: `Oracle::CounterForWatchtowers` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn register_watchtower() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196755`
		//  Estimated: `356514`
		// Minimum execution time: 1_582_699_000 picoseconds.
		Weight::from_parts(1_617_859_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(486))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:129 w:0)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:129 w:0)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:1)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:6 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn ack_observed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215818`
		//  Estimated: `356514`
		// Minimum execution time: 1_676_609_000 picoseconds.
		Weight::from_parts(1_710_009_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(484))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Constitution::Params` (r:18 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:10)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:129 w:10)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:119 w:10)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:1)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn crank_round_close(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `217607`
		//  Estimated: `356514`
		// Minimum execution time: 1_729_419_000 picoseconds.
		Weight::from_parts(1_809_273_429, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			// Standard Error: 584_893
			.saturating_add(Weight::from_parts(30_970_079, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(496))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
	}
	/// Storage: `Oracle::ReserveProbeArmed` (r:1 w:0)
	/// Proof: `Oracle::ReserveProbeArmed` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:20 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:1)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::PhaseFlags` (r:1 w:1)
	/// Proof: `Constitution::PhaseFlags` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Welfare::XcmTrafficEpochs` (r:1 w:1)
	/// Proof: `Welfare::XcmTrafficEpochs` (`max_values`: Some(1), `max_size`: Some(85), added: 580, mode: `MaxEncodedLen`)
	/// Storage: `Welfare::XcmTraffic` (r:1 w:1)
	/// Proof: `Welfare::XcmTraffic` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(2306), added: 2801, mode: `MaxEncodedLen`)
	/// Storage: `ParachainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `ParachainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpMessages` (r:0 w:1)
	/// Proof: `XcmpQueue::OutboundXcmpMessages` (`max_values`: None, `max_size`: Some(65570), added: 68045, mode: `MaxEncodedLen`)
	fn crank_reserve_probe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `14604`
		//  Estimated: `53130`
		// Minimum execution time: 247_030_000 picoseconds.
		Weight::from_parts(271_390_000, 0)
			.saturating_add(Weight::from_parts(0, 53130))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `Constitution::Params` (r:17 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:1)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::PhaseFlags` (r:1 w:1)
	/// Proof: `Constitution::PhaseFlags` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	fn reserve_probe_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13178`
		//  Estimated: `45309`
		// Minimum execution time: 86_420_000 picoseconds.
		Weight::from_parts(92_320_000, 0)
			.saturating_add(Weight::from_parts(0, 45309))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Oracle::Reporters` (r:65 w:0)
	/// Proof: `Oracle::Reporters` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Watchtowers` (r:17 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Rounds` (r:129 w:1)
	/// Proof: `Oracle::Rounds` (`max_values`: None, `max_size`: Some(281), added: 2756, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::RoundSchedules` (r:129 w:1)
	/// Proof: `Oracle::RoundSchedules` (`max_values`: None, `max_size`: Some(41), added: 2516, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ComponentValues` (r:128 w:1)
	/// Proof: `Oracle::ComponentValues` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::ReserveHealth` (r:1 w:0)
	/// Proof: `Oracle::ReserveHealth` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::AckRecords` (r:1 w:1)
	/// Proof: `Oracle::AckRecords` (`max_values`: Some(1), `max_size`: Some(149506), added: 150001, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::Recomputable` (r:1 w:0)
	/// Proof: `Oracle::Recomputable` (`max_values`: Some(1), `max_size`: Some(258), added: 753, mode: `MaxEncodedLen`)
	/// Storage: `Oracle::WatchtowerActive` (r:1 w:0)
	/// Proof: `Oracle::WatchtowerActive` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `MaxEncodedLen`)
	fn adjudicate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `203671`
		//  Estimated: `356514`
		// Minimum execution time: 1_591_019_000 picoseconds.
		Weight::from_parts(1_643_699_000, 0)
			.saturating_add(Weight::from_parts(0, 356514))
			.saturating_add(T::DbWeight::get().reads(472))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}
