
//! Autogenerated weights for `pallet_attestor`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-07-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_attestor
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_attestor.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_attestor`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_attestor::WeightInfo for WeightInfo<T> {
	/// Storage: `Attestor::Members` (r:1 w:1)
	/// Proof: `Attestor::Members` (`max_values`: Some(1), `max_size`: Some(801), added: 1296, mode: `MaxEncodedLen`)
	/// Storage: `Attestor::NextAttestationId` (r:0 w:1)
	/// Proof: `Attestor::NextAttestationId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Attestor::Attestations` (r:0 w:1)
	/// Proof: `Attestor::Attestations` (`max_values`: Some(1), `max_size`: Some(50690), added: 51185, mode: `MaxEncodedLen`)
	fn set_members() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `2286`
		// Minimum execution time: 7_830_000 picoseconds.
		Weight::from_parts(8_010_000, 0)
			.saturating_add(Weight::from_parts(0, 2286))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestor::Members` (r:1 w:1)
	/// Proof: `Attestor::Members` (`max_values`: Some(1), `max_size`: Some(801), added: 1296, mode: `MaxEncodedLen`)
	/// Storage: `Attestor::Attestations` (r:1 w:1)
	/// Proof: `Attestor::Attestations` (`max_values`: Some(1), `max_size`: Some(50690), added: 51185, mode: `MaxEncodedLen`)
	/// Storage: `Attestor::NextAttestationId` (r:1 w:1)
	/// Proof: `Attestor::NextAttestationId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn attest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `30718`
		//  Estimated: `52175`
		// Minimum execution time: 55_050_000 picoseconds.
		Weight::from_parts(55_280_000, 0)
			.saturating_add(Weight::from_parts(0, 52175))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestor::Members` (r:1 w:1)
	/// Proof: `Attestor::Members` (`max_values`: Some(1), `max_size`: Some(801), added: 1296, mode: `MaxEncodedLen`)
	/// Storage: `Attestor::Attestations` (r:1 w:1)
	/// Proof: `Attestor::Attestations` (`max_values`: Some(1), `max_size`: Some(50690), added: 51185, mode: `MaxEncodedLen`)
	/// Storage: `Attestor::NextAttestationId` (r:1 w:1)
	/// Proof: `Attestor::NextAttestationId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn challenge_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `30835`
		//  Estimated: `52175`
		// Minimum execution time: 50_900_000 picoseconds.
		Weight::from_parts(51_360_000, 0)
			.saturating_add(Weight::from_parts(0, 52175))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Attestor::Members` (r:1 w:1)
	/// Proof: `Attestor::Members` (`max_values`: Some(1), `max_size`: Some(801), added: 1296, mode: `MaxEncodedLen`)
	/// Storage: `Attestor::Attestations` (r:1 w:1)
	/// Proof: `Attestor::Attestations` (`max_values`: Some(1), `max_size`: Some(50690), added: 51185, mode: `MaxEncodedLen`)
	/// Storage: `Attestor::NextAttestationId` (r:1 w:1)
	/// Proof: `Attestor::NextAttestationId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `30916`
		//  Estimated: `52175`
		// Minimum execution time: 50_570_000 picoseconds.
		Weight::from_parts(50_930_000, 0)
			.saturating_add(Weight::from_parts(0, 52175))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
