
//! Autogenerated weights for `pallet_conditional_ledger`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /tmp/claude-1000/-home-chralt-development-bleavit--claude-worktrees-futarchy-as-a-service/9d3801fe-68cd-47c4-9868-d1b96e35cb20/n9wt/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_conditional_ledger
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/bleavit-runtime/src/weights/pallet_conditional_ledger.rs
// --unsafe-overwrite-results

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_conditional_ledger`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_conditional_ledger::WeightInfo for WeightInfo<T> {
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `InflowCaps::CumulativeDeposits` (r:1 w:0)
	/// Proof: `InflowCaps::CumulativeDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn split() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2943`
		//  Estimated: `36928`
		// Minimum execution time: 222_430_000 picoseconds.
		Weight::from_parts(231_660_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(44))
			.saturating_add(T::DbWeight::get().writes(35))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn merge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2893`
		//  Estimated: `36928`
		// Minimum execution time: 220_830_000 picoseconds.
		Weight::from_parts(228_150_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(40))
			.saturating_add(T::DbWeight::get().writes(35))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `InflowCaps::CumulativeDeposits` (r:1 w:0)
	/// Proof: `InflowCaps::CumulativeDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn split_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3398`
		//  Estimated: `36928`
		// Minimum execution time: 205_480_000 picoseconds.
		Weight::from_parts(212_550_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(43))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn merge_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3016`
		//  Estimated: `36928`
		// Minimum execution time: 197_070_000 picoseconds.
		Weight::from_parts(204_350_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(39))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `InflowCaps::CumulativeDeposits` (r:1 w:0)
	/// Proof: `InflowCaps::CumulativeDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn split_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3398`
		//  Estimated: `36928`
		// Minimum execution time: 206_390_000 picoseconds.
		Weight::from_parts(212_440_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(43))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn merge_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3014`
		//  Estimated: `36928`
		// Minimum execution time: 196_000_000 picoseconds.
		Weight::from_parts(201_540_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(39))
			.saturating_add(T::DbWeight::get().writes(34))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:28 w:28)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2942`
		//  Estimated: `72866`
		// Minimum execution time: 295_520_000 picoseconds.
		Weight::from_parts(303_350_000, 0)
			.saturating_add(Weight::from_parts(0, 72866))
			.saturating_add(T::DbWeight::get().reads(55))
			.saturating_add(T::DbWeight::get().writes(49))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:5 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `InflowCaps::CumulativeDeposits` (r:1 w:0)
	/// Proof: `InflowCaps::CumulativeDeposits` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn split_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2822`
		//  Estimated: `14025`
		// Minimum execution time: 134_000_000 picoseconds.
		Weight::from_parts(138_790_000, 0)
			.saturating_add(Weight::from_parts(0, 14025))
			.saturating_add(T::DbWeight::get().reads(20))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn merge_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2756`
		//  Estimated: `8811`
		// Minimum execution time: 131_760_000 picoseconds.
		Weight::from_parts(135_630_000, 0)
			.saturating_add(Weight::from_parts(0, 8811))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn resolve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1642`
		//  Estimated: `36256`
		// Minimum execution time: 68_720_000 picoseconds.
		Weight::from_parts(70_700_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(19))
			.saturating_add(T::DbWeight::get().writes(15))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn void() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1642`
		//  Estimated: `36256`
		// Minimum execution time: 70_480_000 picoseconds.
		Weight::from_parts(72_860_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(19))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn settle_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1643`
		//  Estimated: `36256`
		// Minimum execution time: 70_220_000 picoseconds.
		Weight::from_parts(72_290_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(19))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn settle_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1643`
		//  Estimated: `36256`
		// Minimum execution time: 68_990_000 picoseconds.
		Weight::from_parts(71_450_000, 0)
			.saturating_add(Weight::from_parts(0, 36256))
			.saturating_add(T::DbWeight::get().reads(19))
			.saturating_add(T::DbWeight::get().writes(15))
	}
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:2 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineTerminalAt` (r:0 w:1)
	/// Proof: `ConditionalLedger::BaselineTerminalAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn settle_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1515`
		//  Estimated: `6204`
		// Minimum execution time: 34_070_000 picoseconds.
		Weight::from_parts(35_380_000, 0)
			.saturating_add(Weight::from_parts(0, 6204))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn redeem() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2935`
		//  Estimated: `36928`
		// Minimum execution time: 211_430_000 picoseconds.
		Weight::from_parts(225_560_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(40))
			.saturating_add(T::DbWeight::get().writes(35))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:1)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn redeem_scalar() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3086`
		//  Estimated: `36928`
		// Minimum execution time: 212_560_000 picoseconds.
		Weight::from_parts(224_020_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(40))
			.saturating_add(T::DbWeight::get().writes(36))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:1)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn redeem_scalar_pair() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3086`
		//  Estimated: `36928`
		// Minimum execution time: 212_389_000 picoseconds.
		Weight::from_parts(223_150_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(40))
			.saturating_add(T::DbWeight::get().writes(36))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:1)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn redeem_gate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3084`
		//  Estimated: `36928`
		// Minimum execution time: 213_340_000 picoseconds.
		Weight::from_parts(223_970_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(40))
			.saturating_add(T::DbWeight::get().writes(36))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:0)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:14 w:14)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:14 w:14)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn redeem_void() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2926`
		//  Estimated: `36928`
		// Minimum execution time: 206_470_000 picoseconds.
		Weight::from_parts(215_870_000, 0)
			.saturating_add(Weight::from_parts(0, 36928))
			.saturating_add(T::DbWeight::get().reads(40))
			.saturating_add(T::DbWeight::get().writes(35))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:1)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn redeem_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2797`
		//  Estimated: `8811`
		// Minimum execution time: 124_650_000 picoseconds.
		Weight::from_parts(135_930_000, 0)
			.saturating_add(Weight::from_parts(0, 8811))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:1)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:2 w:2)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:1 w:1)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn redeem_baseline_pair() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2797`
		//  Estimated: `8811`
		// Minimum execution time: 125_610_000 picoseconds.
		Weight::from_parts(135_180_000, 0)
			.saturating_add(Weight::from_parts(0, 8811))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `ConditionalLedger::VaultTerminalAt` (r:1 w:1)
	/// Proof: `ConditionalLedger::VaultTerminalAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:9 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Market::ProposalMarketIds` (r:1 w:0)
	/// Proof: `Market::ProposalMarketIds` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:114 w:100)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:100 w:100)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:104 w:104)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::SweptResidueUnreclaimed` (r:1 w:1)
	/// Proof: `FutarchyTreasury::SweptResidueUnreclaimed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::PendingMainCredit` (r:1 w:1)
	/// Proof: `FutarchyTreasury::PendingMainCredit` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	fn sweep_dust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41968`
		//  Estimated: `334518`
		// Minimum execution time: 5_515_320_000 picoseconds.
		Weight::from_parts(5_713_239_000, 0)
			.saturating_add(Weight::from_parts(0, 334518))
			.saturating_add(T::DbWeight::get().reads(439))
			.saturating_add(T::DbWeight::get().writes(314))
	}
	/// Storage: `ConditionalLedger::BaselineTerminalAt` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineTerminalAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:9 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Market::BaselineMarketOf` (r:1 w:0)
	/// Proof: `Market::BaselineMarketOf` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Positions` (r:102 w:100)
	/// Proof: `ConditionalLedger::Positions` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionTotals` (r:2 w:2)
	/// Proof: `ConditionalLedger::PositionTotals` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::PositionCount` (r:100 w:100)
	/// Proof: `ConditionalLedger::PositionCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:1)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:100 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:104 w:104)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:1)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::SweptResidueUnreclaimed` (r:1 w:1)
	/// Proof: `FutarchyTreasury::SweptResidueUnreclaimed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::PendingMainCredit` (r:1 w:1)
	/// Proof: `FutarchyTreasury::PendingMainCredit` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	fn sweep_dust_baseline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41720`
		//  Estimated: `334518`
		// Minimum execution time: 5_045_839_000 picoseconds.
		Weight::from_parts(5_229_810_000, 0)
			.saturating_add(Weight::from_parts(0, 334518))
			.saturating_add(T::DbWeight::get().reads(427))
			.saturating_add(T::DbWeight::get().writes(314))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:0)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::RedemptionFeesAccrued` (r:1 w:1)
	/// Proof: `ConditionalLedger::RedemptionFeesAccrued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:4 w:4)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::PendingMainCredit` (r:1 w:1)
	/// Proof: `FutarchyTreasury::PendingMainCredit` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:7 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	fn sweep_redemption_fees() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12720`
		//  Estimated: `26846`
		// Minimum execution time: 125_470_000 picoseconds.
		Weight::from_parts(133_290_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `ConditionalLedger::SplitPausedUntil` (r:0 w:1)
	/// Proof: `ConditionalLedger::SplitPausedUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn set_split_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_790_000 picoseconds.
		Weight::from_parts(4_250_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ConditionalLedger::FrozenUntil` (r:1 w:1)
	/// Proof: `ConditionalLedger::FrozenUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::FreezeRenewed` (r:0 w:1)
	/// Proof: `ConditionalLedger::FreezeRenewed` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_frozen() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `1489`
		// Minimum execution time: 5_770_000 picoseconds.
		Weight::from_parts(6_440_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:1 w:0)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::DepositsHeld` (r:1 w:0)
	/// Proof: `ConditionalLedger::DepositsHeld` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::LedgerDrifted` (r:1 w:1)
	/// Proof: `ConditionalLedger::LedgerDrifted` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::PendingMainCredit` (r:1 w:1)
	/// Proof: `FutarchyTreasury::PendingMainCredit` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:7 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::LastReconciliation` (r:0 w:1)
	/// Proof: `ConditionalLedger::LastReconciliation` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	fn reconcile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12719`
		//  Estimated: `26846`
		// Minimum execution time: 97_080_000 picoseconds.
		Weight::from_parts(108_050_000, 0)
			.saturating_add(Weight::from_parts(0, 26846))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: UNKNOWN KEY `0x94eec1b9345db53a85e5f5b9e9532fe44e7b9012096b41c4eb3aaf947f6ea429` (r:1 w:0)
	/// Proof: UNKNOWN KEY `0x94eec1b9345db53a85e5f5b9e9532fe44e7b9012096b41c4eb3aaf947f6ea429` (r:1 w:0)
	/// Storage: `ConditionalLedger::Vaults` (r:2 w:0)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	fn migration_step_row() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `277`
		//  Estimated: `6308`
		// Minimum execution time: 8_190_000 picoseconds.
		Weight::from_parts(8_730_000, 0)
			.saturating_add(Weight::from_parts(0, 6308))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: UNKNOWN KEY `0x94eec1b9345db53a85e5f5b9e9532fe44e7b9012096b41c4eb3aaf947f6ea429` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x94eec1b9345db53a85e5f5b9e9532fe44e7b9012096b41c4eb3aaf947f6ea429` (r:1 w:1)
	/// Storage: `ConditionalLedger::BaselineVaults` (r:1 w:0)
	/// Proof: `ConditionalLedger::BaselineVaults` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::TotalEscrowed` (r:0 w:1)
	/// Proof: `ConditionalLedger::TotalEscrowed` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn migration_step_terminal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79`
		//  Estimated: `3544`
		// Minimum execution time: 6_420_000 picoseconds.
		Weight::from_parts(7_140_000, 0)
			.saturating_add(Weight::from_parts(0, 3544))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
