
//! Autogenerated weights for `pallet_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallet
// pallet_registry
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// /tmp/claude-1000/-home-development-bleavit/b40139b1-6248-4c1a-ad60-57e786f83c15/scratchpad/sq141-pallet_registry.rs
// --unsafe-overwrite-results

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_registry`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_registry::WeightInfo for WeightInfo<T> {
	/// Storage: `Epoch::CohortSchedules` (r:5 w:0)
	/// Proof: `Epoch::CohortSchedules` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:20 w:0)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Welfare::MetricSpecs` (r:1 w:0)
	/// Proof: `Welfare::MetricSpecs` (`max_values`: None, `max_size`: Some(3507), added: 5982, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:64 w:1)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:9 w:8)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn file() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `15489`
		//  Estimated: `171934`
		// Minimum execution time: 451_490_000 picoseconds.
		Weight::from_parts(477_970_000, 0)
			.saturating_add(Weight::from_parts(0, 171934))
			.saturating_add(T::DbWeight::get().reads(113))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:1)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:9 w:8)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn challenge_filing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11208`
		//  Estimated: `174605`
		// Minimum execution time: 335_150_000 picoseconds.
		Weight::from_parts(355_920_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(86))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `Oracle::Watchtowers` (r:1 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::AckRecords` (r:1 w:1)
	/// Proof: `MilestoneRegistry::AckRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:10 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:1)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:9 w:8)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn ack_observed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21955`
		//  Estimated: `174605`
		// Minimum execution time: 395_180_000 picoseconds.
		Weight::from_parts(419_440_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(95))
			.saturating_add(T::DbWeight::get().writes(18))
	}
	/// Storage: `Constitution::Params` (r:10 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:20)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:9 w:8)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	fn crank_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21704`
		//  Estimated: `174605`
		// Minimum execution time: 974_761_000 picoseconds.
		Weight::from_parts(1_038_551_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(94))
			.saturating_add(T::DbWeight::get().writes(37))
	}
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:1)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:9 w:8)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11310`
		//  Estimated: `174605`
		// Minimum execution time: 363_580_000 picoseconds.
		Weight::from_parts(384_390_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(87))
			.saturating_add(T::DbWeight::get().writes(17))
	}
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Welfare::MetricSpecs` (r:1 w:0)
	/// Proof: `Welfare::MetricSpecs` (`max_values`: None, `max_size`: Some(3507), added: 5982, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:4 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:0)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:8 w:8)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::ClosedAt` (r:0 w:1)
	/// Proof: `MilestoneRegistry::ClosedAt` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	fn close_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10221`
		//  Estimated: `174605`
		// Minimum execution time: 304_631_000 picoseconds.
		Weight::from_parts(321_670_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(85))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	/// Storage: `MilestoneRegistry::ClosedAt` (r:1 w:1)
	/// Proof: `MilestoneRegistry::ClosedAt` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:12 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:64)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:4 w:3)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:9 w:8)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::AckRecords` (r:128 w:128)
	/// Proof: `MilestoneRegistry::AckRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn reap_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `30005`
		//  Estimated: `329054`
		// Minimum execution time: 1_056_751_000 picoseconds.
		Weight::from_parts(1_110_100_000, 0)
			.saturating_add(Weight::from_parts(0, 329054))
			.saturating_add(T::DbWeight::get().reads(224))
			.saturating_add(T::DbWeight::get().writes(208))
	}
}
