
//! Autogenerated weights for `pallet_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// /home/chralt/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallets
// pallet_registry
// --all
// --steps
// 50
// --repeat
// 20
// --min-duration
// 0
// --unsafe-overwrite-results
// --output
// runtime/bleavit-runtime/src/weights/pallet_registry.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_registry`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_registry::WeightInfo for WeightInfo<T> {
	/// Storage: `Epoch::CohortSchedules` (r:5 w:0)
	/// Proof: `Epoch::CohortSchedules` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:20 w:0)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:14 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Welfare::MetricSpecs` (r:1 w:0)
	/// Proof: `Welfare::MetricSpecs` (`max_values`: None, `max_size`: Some(3379), added: 5854, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:64 w:1)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn file() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `16453`
		//  Estimated: `171934`
		// Minimum execution time: 513_700_000 picoseconds.
		Weight::from_parts(518_310_000, 0)
			.saturating_add(Weight::from_parts(0, 171934))
			.saturating_add(T::DbWeight::get().reads(119))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `IncidentRegistry::Filings` (r:65 w:1)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:14 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn challenge_filing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12323`
		//  Estimated: `174605`
		// Minimum execution time: 391_080_000 picoseconds.
		Weight::from_parts(395_040_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(92))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `Oracle::Watchtowers` (r:1 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::AckRecords` (r:1 w:1)
	/// Proof: `IncidentRegistry::AckRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:20 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:1)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn ack_observed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `23032`
		//  Estimated: `174605`
		// Minimum execution time: 446_239_000 picoseconds.
		Weight::from_parts(450_880_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(101))
			.saturating_add(T::DbWeight::get().writes(14))
	}
	/// Storage: `Constitution::Params` (r:20 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:20)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	fn crank_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `22854`
		//  Estimated: `174605`
		// Minimum execution time: 1_103_739_000 picoseconds.
		Weight::from_parts(1_108_950_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(100))
			.saturating_add(T::DbWeight::get().writes(33))
	}
	/// Storage: `Constitution::Params` (r:14 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:1)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12424`
		//  Estimated: `174605`
		// Minimum execution time: 425_440_000 picoseconds.
		Weight::from_parts(428_300_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(93))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	/// Storage: `IncidentRegistry::FilingCount` (r:5 w:4)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:14 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:0)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:4 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::ClosedAt` (r:0 w:1)
	/// Proof: `IncidentRegistry::ClosedAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn close_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `11061`
		//  Estimated: `174605`
		// Minimum execution time: 357_190_000 picoseconds.
		Weight::from_parts(361_770_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(90))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `IncidentRegistry::ClosedAt` (r:1 w:1)
	/// Proof: `IncidentRegistry::ClosedAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:22 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Filings` (r:65 w:64)
	/// Proof: `IncidentRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::FilingCount` (r:4 w:3)
	/// Proof: `IncidentRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::Aggregates` (r:5 w:4)
	/// Proof: `IncidentRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `IncidentRegistry::AckRecords` (r:128 w:128)
	/// Proof: `IncidentRegistry::AckRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn reap_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31022`
		//  Estimated: `329054`
		// Minimum execution time: 678_769_000 picoseconds.
		Weight::from_parts(688_620_000, 0)
			.saturating_add(Weight::from_parts(0, 329054))
			.saturating_add(T::DbWeight::get().reads(230))
			.saturating_add(T::DbWeight::get().writes(204))
	}
}
