
//! Autogenerated weights for `pallet_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-07-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `msi-pro-b650-s`, CPU: `AMD Ryzen 9 7950X3D 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// /home/chralt/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/bleavit-runtime/bleavit_runtime.compact.compressed.wasm
// --pallets
// pallet_registry
// --all
// --steps
// 50
// --repeat
// 20
// --min-duration
// 0
// --unsafe-overwrite-results
// --output
// runtime/bleavit-runtime/src/weights/pallet_registry.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_registry`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_registry::WeightInfo for WeightInfo<T> {
	/// Storage: `Epoch::CohortSchedules` (r:5 w:0)
	/// Proof: `Epoch::CohortSchedules` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
	/// Storage: `ConditionalLedger::Vaults` (r:20 w:0)
	/// Proof: `ConditionalLedger::Vaults` (`max_values`: None, `max_size`: Some(184), added: 2659, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Welfare::MetricSpecs` (r:1 w:0)
	/// Proof: `Welfare::MetricSpecs` (`max_values`: None, `max_size`: Some(3379), added: 5854, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:64 w:1)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:5 w:4)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn file() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `14803`
		//  Estimated: `171934`
		// Minimum execution time: 412_200_000 picoseconds.
		Weight::from_parts(424_340_000, 0)
			.saturating_add(Weight::from_parts(0, 171934))
			.saturating_add(T::DbWeight::get().reads(108))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:1)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:5 w:4)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn challenge_filing() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10712`
		//  Estimated: `174605`
		// Minimum execution time: 316_540_000 picoseconds.
		Weight::from_parts(322_070_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(81))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `Oracle::Watchtowers` (r:1 w:0)
	/// Proof: `Oracle::Watchtowers` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::AckRecords` (r:1 w:1)
	/// Proof: `MilestoneRegistry::AckRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:9 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:1)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:5 w:4)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn ack_observed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21459`
		//  Estimated: `174605`
		// Minimum execution time: 368_550_000 picoseconds.
		Weight::from_parts(377_920_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(90))
			.saturating_add(T::DbWeight::get().writes(14))
	}
	/// Storage: `Constitution::Params` (r:9 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:20)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:5 w:4)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	fn crank_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21208`
		//  Estimated: `174605`
		// Minimum execution time: 934_590_000 picoseconds.
		Weight::from_parts(963_900_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(89))
			.saturating_add(T::DbWeight::get().writes(33))
	}
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:1)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:5 w:4)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:3 w:3)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10814`
		//  Estimated: `174605`
		// Minimum execution time: 340_650_000 picoseconds.
		Weight::from_parts(343_560_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(82))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	/// Storage: `MilestoneRegistry::FilingCount` (r:5 w:4)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::Schedule` (r:1 w:0)
	/// Proof: `Epoch::Schedule` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:3 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:0)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:4 w:4)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::ClosedAt` (r:0 w:1)
	/// Proof: `MilestoneRegistry::ClosedAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn close_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9452`
		//  Estimated: `174605`
		// Minimum execution time: 285_900_000 picoseconds.
		Weight::from_parts(294_390_000, 0)
			.saturating_add(Weight::from_parts(0, 174605))
			.saturating_add(T::DbWeight::get().reads(79))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `MilestoneRegistry::ClosedAt` (r:1 w:1)
	/// Proof: `MilestoneRegistry::ClosedAt` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `Constitution::Params` (r:11 w:0)
	/// Proof: `Constitution::Params` (`max_values`: None, `max_size`: Some(132), added: 2607, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Filings` (r:65 w:64)
	/// Proof: `MilestoneRegistry::Filings` (`max_values`: None, `max_size`: Some(196), added: 2671, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::FilingCount` (r:4 w:3)
	/// Proof: `MilestoneRegistry::FilingCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::Aggregates` (r:5 w:4)
	/// Proof: `MilestoneRegistry::Aggregates` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `MilestoneRegistry::AckRecords` (r:128 w:128)
	/// Proof: `MilestoneRegistry::AckRecords` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `FutarchyTreasury::State` (r:1 w:1)
	/// Proof: `FutarchyTreasury::State` (`max_values`: Some(1), `max_size`: Some(25361), added: 25856, mode: `MaxEncodedLen`)
	/// Storage: `Epoch::EpochOf` (r:1 w:0)
	/// Proof: `Epoch::EpochOf` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Asset` (r:1 w:1)
	/// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
	/// Storage: `ForeignAssets::Account` (r:2 w:2)
	/// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
	fn reap_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `29483`
		//  Estimated: `329054`
		// Minimum execution time: 572_360_000 picoseconds.
		Weight::from_parts(584_300_000, 0)
			.saturating_add(Weight::from_parts(0, 329054))
			.saturating_add(T::DbWeight::get().reads(219))
			.saturating_add(T::DbWeight::get().writes(204))
	}
}
