/**
 * GENERATED — do not edit. Source: `tools/release/surface-manifest.json` (contract v23).
 * Regenerate: `pnpm -C app run surface:generate`; verified by `pnpm -C app run surface:check`.
 *
 * 10 §5.2's `CRITICAL_SURFACE`: every runtime API, storage item, constant and event the
 * app binds to, in the form a PAPI compatibility probe can ask about. Hand-listing it is
 * banned (app-code rule 7) because a hand-maintained copy of a frozen surface is
 * consistent with everyone who reads it and compared to nothing.
 *
 * **What is not here, and why.** The manifest carries no `call` entries — doc 02 freezes
 * the *read* contract (APIs, views, events, storage, constants, identity) and has no
 * extrinsic section at all — while 10 §5.2 names calls as part of `CRITICAL_SURFACE` and
 * 10 §3.2 makes `restricted` signing "per-surface", whose unit is exactly the call. That
 * gap is SQ-574. Until it closes, `callIsProven()` answers `false` for every call, which
 * is INV-FE-12's fail-closed reading: an unproven capability is *absent*, and absence
 * disables the dependent surface with a named reason.
 */

/** The PAPI compat group that answers for a surface (`api.getStaticApis().compat[group]`). */
export type CompatGroup = 'apis' | 'query' | 'constants' | 'event';

export interface CriticalSurfaceEntry {
  readonly id: string;
  readonly compatGroup: CompatGroup;
  /** Pallet name, or runtime-API trait name for `apis`. */
  readonly pallet: string;
  readonly member: string;
  readonly required: boolean;
  readonly citation: string;
}

export const INTEGRATION_CONTRACT_VERSION = 23;

/** Manifest entries with no metadata surface to probe (raw fixed-layout key, chain properties). */
export const UNPROBED_MANIFEST_ENTRIES = 2;

export const CRITICAL_SURFACE: readonly CriticalSurfaceEntry[] = [
  { id: "api.account_positions", compatGroup: "apis", pallet: "FutarchyApi", member: "account_positions", required: true, citation: "02 §3" },
  { id: "api.decision_stats", compatGroup: "apis", pallet: "FutarchyApi", member: "decision_stats", required: true, citation: "02 §3" },
  { id: "api.epoch_status", compatGroup: "apis", pallet: "FutarchyApi", member: "epoch_status", required: true, citation: "02 §3" },
  { id: "api.execution_queue", compatGroup: "apis", pallet: "FutarchyApi", member: "execution_queue", required: true, citation: "02 §3" },
  { id: "api.hosted_report", compatGroup: "apis", pallet: "FutarchyApi", member: "hosted_report", required: true, citation: "02 §3; 02 §4a" },
  { id: "api.nav", compatGroup: "apis", pallet: "FutarchyApi", member: "nav", required: true, citation: "02 §3" },
  { id: "api.open_oracle_rounds", compatGroup: "apis", pallet: "FutarchyApi", member: "open_oracle_rounds", required: true, citation: "02 §3" },
  { id: "api.params", compatGroup: "apis", pallet: "FutarchyApi", member: "params", required: true, citation: "02 §3" },
  { id: "api.proposal_summaries", compatGroup: "apis", pallet: "FutarchyApi", member: "proposal_summaries", required: true, citation: "02 §3" },
  { id: "api.quote", compatGroup: "apis", pallet: "FutarchyApi", member: "quote", required: true, citation: "02 §3" },
  { id: "api.recent_cohorts", compatGroup: "apis", pallet: "FutarchyApi", member: "recent_cohorts", required: true, citation: "02 §3" },
  { id: "api.service_positions", compatGroup: "apis", pallet: "FutarchyApi", member: "service_positions", required: true, citation: "02 §3; 02 §7.1" },
  { id: "api.welfare_current", compatGroup: "apis", pallet: "FutarchyApi", member: "welfare_current", required: true, citation: "02 §3" },
  { id: "constant.client_registry.client_bond", compatGroup: "constants", pallet: "ClientRegistry", member: "ClientBond", required: true, citation: "02 §4a; 02 §9" },
  { id: "constant.decision.delta_floors", compatGroup: "constants", pallet: "Epoch", member: "DecisionDeltaFloors", required: true, citation: "02 §9" },
  { id: "constant.decision.extension", compatGroup: "constants", pallet: "Epoch", member: "DecisionExtension", required: true, citation: "02 §9" },
  { id: "constant.decision.sigma_floors", compatGroup: "constants", pallet: "Epoch", member: "DecisionSigmaFloors", required: true, citation: "02 §9" },
  { id: "constant.decision.window_floor", compatGroup: "constants", pallet: "Epoch", member: "DecisionWindowFloor", required: true, citation: "02 §9" },
  { id: "constant.epoch.books_per_proposal", compatGroup: "constants", pallet: "Epoch", member: "MaxBooksPerProposal", required: true, citation: "02 §9" },
  { id: "constant.epoch.length_floor", compatGroup: "constants", pallet: "Epoch", member: "MinEpochLength", required: true, citation: "02 §9" },
  { id: "constant.epoch.max_intake_queue", compatGroup: "constants", pallet: "Epoch", member: "MaxIntakeQueue", required: true, citation: "02 §9" },
  { id: "constant.epoch.max_live_proposals", compatGroup: "constants", pallet: "Epoch", member: "MaxLiveProposals", required: true, citation: "02 §9" },
  { id: "constant.epoch.phase_offsets", compatGroup: "constants", pallet: "Epoch", member: "PhaseOffsets", required: true, citation: "02 §9" },
  { id: "constant.epoch.recent_cohorts", compatGroup: "constants", pallet: "Epoch", member: "RecentCohortSummariesBound", required: true, citation: "02 §9" },
  { id: "constant.epoch.treasury_bond_ask_bps", compatGroup: "constants", pallet: "Epoch", member: "TreasuryBondAskBps", required: true, citation: "02 §9; 08 §7" },
  { id: "constant.execution_guard.descriptor_lead_time", compatGroup: "constants", pallet: "ExecutionGuard", member: "DescriptorLeadTime", required: true, citation: "02 §9" },
  { id: "constant.execution_guard.grace_floor", compatGroup: "constants", pallet: "ExecutionGuard", member: "ExecutionGraceFloor", required: true, citation: "02 §9" },
  { id: "constant.execution_guard.timelock_floor", compatGroup: "constants", pallet: "ExecutionGuard", member: "ExecutionTimelockFloor", required: true, citation: "02 §9" },
  { id: "constant.identity.contract_version", compatGroup: "constants", pallet: "Constitution", member: "INTEGRATION_CONTRACT_VERSION", required: true, citation: "02 §8; 02 §13" },
  { id: "constant.identity.ss58_prefix", compatGroup: "constants", pallet: "System", member: "SS58Prefix", required: true, citation: "02 §8" },
  { id: "constant.identity.vit_existential_deposit", compatGroup: "constants", pallet: "Balances", member: "ExistentialDeposit", required: true, citation: "02 §8" },
  { id: "constant.ledger.max_positions_per_account", compatGroup: "constants", pallet: "ConditionalLedger", member: "MaxPositionsPerAccount", required: true, citation: "02 §9" },
  { id: "constant.ledger.min_split", compatGroup: "constants", pallet: "ConditionalLedger", member: "MinSplit", required: true, citation: "02 §9" },
  { id: "constant.ledger.min_transfer", compatGroup: "constants", pallet: "ConditionalLedger", member: "MinTransfer", required: true, citation: "02 §9" },
  { id: "constant.ledger.position_deposit", compatGroup: "constants", pallet: "ConditionalLedger", member: "PositionDeposit", required: true, citation: "02 §9" },
  { id: "constant.ledger.service_id_base", compatGroup: "constants", pallet: "ConditionalLedger", member: "ServiceIdBase", required: true, citation: "02 §9" },
  { id: "constant.market.gate_eps_floor", compatGroup: "constants", pallet: "Market", member: "GateEpsFloor", required: true, citation: "02 §9" },
  { id: "constant.market.gate_p_max_ceiling", compatGroup: "constants", pallet: "Market", member: "GatePMaxCeiling", required: true, citation: "02 §9" },
  { id: "constant.market.max_all_stored_markets", compatGroup: "constants", pallet: "Market", member: "MaxAllStoredMarkets", required: true, citation: "02 §9" },
  { id: "constant.market.max_live_external_markets", compatGroup: "constants", pallet: "Market", member: "MaxLiveExternalMarkets", required: true, citation: "02 §9" },
  { id: "constant.market.max_live_markets", compatGroup: "constants", pallet: "Market", member: "MaxLiveMarkets", required: true, citation: "02 §9" },
  { id: "constant.market.max_stored_external_markets", compatGroup: "constants", pallet: "Market", member: "MaxStoredExternalMarkets", required: true, citation: "02 §9" },
  { id: "constant.market.max_stored_markets", compatGroup: "constants", pallet: "Market", member: "MaxStoredMarkets", required: true, citation: "02 §9" },
  { id: "constant.market.max_trade_ratio", compatGroup: "constants", pallet: "Market", member: "MaxTradeRatio", required: true, citation: "02 §9" },
  { id: "constant.market.min_trade", compatGroup: "constants", pallet: "Market", member: "MinTrade", required: true, citation: "02 §9" },
  { id: "constant.question_service.attestors_min", compatGroup: "constants", pallet: "QuestionService", member: "AttestorsMin", required: true, citation: "02 §4a; 02 §9" },
  { id: "constant.question_service.epsilon_min", compatGroup: "constants", pallet: "QuestionService", member: "EpsilonMin", required: true, citation: "02 §4a; 02 §9" },
  { id: "constant.question_service.fee_floor", compatGroup: "constants", pallet: "QuestionService", member: "FeeFloor", required: true, citation: "02 §4a; 02 §9" },
  { id: "constant.question_service.max_live", compatGroup: "constants", pallet: "QuestionService", member: "MaxLive", required: true, citation: "02 §4a; 02 §9" },
  { id: "constant.question_service.max_window", compatGroup: "constants", pallet: "QuestionService", member: "MaxWindow", required: true, citation: "02 §4a; 02 §9" },
  { id: "constant.registry.archive_delay.incident", compatGroup: "constants", pallet: "IncidentRegistry", member: "ArchiveDelay", required: true, citation: "02 §9" },
  { id: "constant.registry.archive_delay.milestone", compatGroup: "constants", pallet: "MilestoneRegistry", member: "ArchiveDelay", required: true, citation: "02 §9" },
  { id: "event.attestor.attestation_challenged", compatGroup: "event", pallet: "Attestor", member: "AttestationChallenged", required: true, citation: "02 §6" },
  { id: "event.attestor.attestation_revoked", compatGroup: "event", pallet: "Attestor", member: "AttestationRevoked", required: true, citation: "02 §6" },
  { id: "event.attestor.attestation_submitted", compatGroup: "event", pallet: "Attestor", member: "AttestationSubmitted", required: true, citation: "02 §6" },
  { id: "event.attestor.attestor_ejected", compatGroup: "event", pallet: "Attestor", member: "AttestorEjected", required: true, citation: "02 §6" },
  { id: "event.attestor.attestor_removed_for_cause", compatGroup: "event", pallet: "Attestor", member: "AttestorRemovedForCause", required: true, citation: "02 §6" },
  { id: "event.attestor.challenge_resolved", compatGroup: "event", pallet: "Attestor", member: "ChallengeResolved", required: true, citation: "02 §6" },
  { id: "event.attestor.members_set", compatGroup: "event", pallet: "Attestor", member: "MembersSet", required: true, citation: "02 §6" },
  { id: "event.epoch.baseline_carried", compatGroup: "event", pallet: "Epoch", member: "BaselineCarried", required: true, citation: "02 §6" },
  { id: "event.epoch.cohort_settled", compatGroup: "event", pallet: "Epoch", member: "CohortSettled", required: true, citation: "02 §6" },
  { id: "event.epoch.cohort_voided", compatGroup: "event", pallet: "Epoch", member: "CohortVoided", required: true, citation: "02 §6" },
  { id: "event.epoch.decision_extended", compatGroup: "event", pallet: "Epoch", member: "DecisionExtended", required: true, citation: "02 §6" },
  { id: "event.epoch.intake_slashed", compatGroup: "event", pallet: "Epoch", member: "IntakeSlashed", required: true, citation: "02 §6" },
  { id: "event.epoch.mandate_expired", compatGroup: "event", pallet: "Epoch", member: "MandateExpired", required: true, citation: "02 §6" },
  { id: "event.epoch.markets_opened", compatGroup: "event", pallet: "Epoch", member: "MarketsOpened", required: true, citation: "02 §6" },
  { id: "event.epoch.measurement_started", compatGroup: "event", pallet: "Epoch", member: "MeasurementStarted", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_cancelled", compatGroup: "event", pallet: "Epoch", member: "ProposalCancelled", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_deferred", compatGroup: "event", pallet: "Epoch", member: "ProposalDeferred", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_delayed", compatGroup: "event", pallet: "Epoch", member: "ProposalDelayed", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_force_rejected", compatGroup: "event", pallet: "Epoch", member: "ProposalForceRejected", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_qualified", compatGroup: "event", pallet: "Epoch", member: "ProposalQualified", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_queued", compatGroup: "event", pallet: "Epoch", member: "ProposalQueued", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_rejected", compatGroup: "event", pallet: "Epoch", member: "ProposalRejected", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_submitted", compatGroup: "event", pallet: "Epoch", member: "ProposalSubmitted", required: true, citation: "02 §6" },
  { id: "event.epoch.proposal_withdrawn", compatGroup: "event", pallet: "Epoch", member: "ProposalWithdrawn", required: true, citation: "02 §6" },
  { id: "event.epoch.rerun_opened", compatGroup: "event", pallet: "Epoch", member: "RerunOpened", required: true, citation: "02 §6" },
  { id: "event.epoch.rerun_scheduled", compatGroup: "event", pallet: "Epoch", member: "RerunScheduled", required: true, citation: "02 §6" },
  { id: "event.epoch.screening_started", compatGroup: "event", pallet: "Epoch", member: "ScreeningStarted", required: true, citation: "02 §6" },
  { id: "event.epoch.slots_shrunk", compatGroup: "event", pallet: "Epoch", member: "SlotsShrunk", required: true, citation: "02 §6" },
  { id: "event.execution_guard.enqueued", compatGroup: "event", pallet: "ExecutionGuard", member: "Enqueued", required: true, citation: "02 §6" },
  { id: "event.execution_guard.executed", compatGroup: "event", pallet: "ExecutionGuard", member: "Executed", required: true, citation: "02 §6" },
  { id: "event.execution_guard.execution_failed", compatGroup: "event", pallet: "ExecutionGuard", member: "ExecutionFailed", required: true, citation: "02 §6" },
  { id: "event.execution_guard.preimage_unpinned", compatGroup: "event", pallet: "ExecutionGuard", member: "PreimageUnpinned", required: true, citation: "02 §6" },
  { id: "event.execution_guard.ratified", compatGroup: "event", pallet: "ExecutionGuard", member: "Ratified", required: true, citation: "02 §6" },
  { id: "event.execution_guard.rejected", compatGroup: "event", pallet: "ExecutionGuard", member: "Rejected", required: true, citation: "02 §6" },
  { id: "event.execution_guard.upgrade_aborted", compatGroup: "event", pallet: "ExecutionGuard", member: "UpgradeAborted", required: true, citation: "02 §6" },
  { id: "event.execution_guard.upgrade_applied", compatGroup: "event", pallet: "ExecutionGuard", member: "UpgradeApplied", required: true, citation: "02 §6" },
  { id: "event.execution_guard.upgrade_authorized", compatGroup: "event", pallet: "ExecutionGuard", member: "UpgradeAuthorized", required: true, citation: "02 §6" },
  { id: "event.guardian.action", compatGroup: "event", pallet: "Guardian", member: "GuardianAction", required: true, citation: "02 §6" },
  { id: "event.guardian.action_approved", compatGroup: "event", pallet: "Guardian", member: "ActionApproved", required: true, citation: "02 §6" },
  { id: "event.guardian.action_proposed", compatGroup: "event", pallet: "Guardian", member: "ActionProposed", required: true, citation: "02 §6" },
  { id: "event.guardian.action_ratified", compatGroup: "event", pallet: "Guardian", member: "ActionRatified", required: true, citation: "02 §6" },
  { id: "event.guardian.force_rerun", compatGroup: "event", pallet: "Guardian", member: "ForceRerun", required: true, citation: "02 §6" },
  { id: "event.guardian.members_set", compatGroup: "event", pallet: "Guardian", member: "MembersSet", required: true, citation: "02 §6" },
  { id: "event.guardian.playbook_activated", compatGroup: "event", pallet: "Guardian", member: "PlaybookActivated", required: true, citation: "02 §6" },
  { id: "event.guardian.playbook_expired", compatGroup: "event", pallet: "Guardian", member: "PlaybookExpired", required: true, citation: "02 §6" },
  { id: "event.guardian.playbook_registration_set", compatGroup: "event", pallet: "Guardian", member: "PlaybookRegistrationSet", required: true, citation: "02 §6" },
  { id: "event.guardian.playbook_renewed", compatGroup: "event", pallet: "Guardian", member: "PlaybookRenewed", required: true, citation: "02 §6" },
  { id: "event.guardian.recall_enacted", compatGroup: "event", pallet: "Guardian", member: "RecallEnacted", required: true, citation: "02 §6" },
  { id: "event.guardian.recall_scheduled", compatGroup: "event", pallet: "Guardian", member: "RecallScheduled", required: true, citation: "02 §6" },
  { id: "event.guardian.review_failed", compatGroup: "event", pallet: "Guardian", member: "ReviewFailed", required: true, citation: "02 §6" },
  { id: "event.guardian.review_scheduled", compatGroup: "event", pallet: "Guardian", member: "ReviewScheduled", required: true, citation: "02 §6" },
  { id: "event.ledger.baseline_merged", compatGroup: "event", pallet: "ConditionalLedger", member: "BaselineMerged", required: true, citation: "02 §6" },
  { id: "event.ledger.baseline_redeemed", compatGroup: "event", pallet: "ConditionalLedger", member: "BaselineRedeemed", required: true, citation: "02 §6" },
  { id: "event.ledger.baseline_settled", compatGroup: "event", pallet: "ConditionalLedger", member: "BaselineSettled", required: true, citation: "02 §6" },
  { id: "event.ledger.baseline_split", compatGroup: "event", pallet: "ConditionalLedger", member: "BaselineSplit", required: true, citation: "02 §6" },
  { id: "event.ledger.baseline_vault_reaped", compatGroup: "event", pallet: "ConditionalLedger", member: "BaselineVaultReaped", required: true, citation: "02 §6" },
  { id: "event.ledger.gate_merged", compatGroup: "event", pallet: "ConditionalLedger", member: "GateMerged", required: true, citation: "02 §6" },
  { id: "event.ledger.gate_redeemed", compatGroup: "event", pallet: "ConditionalLedger", member: "GateRedeemed", required: true, citation: "02 §6" },
  { id: "event.ledger.gate_settled", compatGroup: "event", pallet: "ConditionalLedger", member: "GateSettled", required: true, citation: "02 §6" },
  { id: "event.ledger.gate_split", compatGroup: "event", pallet: "ConditionalLedger", member: "GateSplit", required: true, citation: "02 §6" },
  { id: "event.ledger.merged", compatGroup: "event", pallet: "ConditionalLedger", member: "Merged", required: true, citation: "02 §6" },
  { id: "event.ledger.position_transferred", compatGroup: "event", pallet: "ConditionalLedger", member: "PositionTransferred", required: true, citation: "02 §6" },
  { id: "event.ledger.redeemed", compatGroup: "event", pallet: "ConditionalLedger", member: "Redeemed", required: true, citation: "02 §6" },
  { id: "event.ledger.redemption_fees_swept", compatGroup: "event", pallet: "ConditionalLedger", member: "RedemptionFeesSwept", required: true, citation: "02 §6" },
  { id: "event.ledger.scalar_merged", compatGroup: "event", pallet: "ConditionalLedger", member: "ScalarMerged", required: true, citation: "02 §6" },
  { id: "event.ledger.scalar_pair_redeemed", compatGroup: "event", pallet: "ConditionalLedger", member: "ScalarPairRedeemed", required: true, citation: "02 §6" },
  { id: "event.ledger.scalar_redeemed", compatGroup: "event", pallet: "ConditionalLedger", member: "ScalarRedeemed", required: true, citation: "02 §6" },
  { id: "event.ledger.scalar_settlement_set", compatGroup: "event", pallet: "ConditionalLedger", member: "ScalarSettlementSet", required: true, citation: "02 §6" },
  { id: "event.ledger.scalar_split", compatGroup: "event", pallet: "ConditionalLedger", member: "ScalarSplit", required: true, citation: "02 §6" },
  { id: "event.ledger.split", compatGroup: "event", pallet: "ConditionalLedger", member: "Split", required: true, citation: "02 §6" },
  { id: "event.ledger.vault_reaped", compatGroup: "event", pallet: "ConditionalLedger", member: "VaultReaped", required: true, citation: "02 §6" },
  { id: "event.ledger.vault_resolved", compatGroup: "event", pallet: "ConditionalLedger", member: "VaultResolved", required: true, citation: "02 §6" },
  { id: "event.ledger.vault_voided", compatGroup: "event", pallet: "ConditionalLedger", member: "VaultVoided", required: true, citation: "02 §6" },
  { id: "event.ledger.void_redeemed", compatGroup: "event", pallet: "ConditionalLedger", member: "VoidRedeemed", required: true, citation: "02 §6" },
  { id: "event.market.closed", compatGroup: "event", pallet: "Market", member: "MarketClosed", required: true, citation: "02 §5; 02 §6" },
  { id: "event.market.created", compatGroup: "event", pallet: "Market", member: "MarketCreated", required: true, citation: "02 §5; 02 §6" },
  { id: "event.market.external_revenue_swept", compatGroup: "event", pallet: "Market", member: "ExternalRevenueSwept", required: true, citation: "02 §5; 02 §6" },
  { id: "event.market.observed", compatGroup: "event", pallet: "Market", member: "Observed", required: true, citation: "02 §5; 02 §6" },
  { id: "event.market.reaped", compatGroup: "event", pallet: "Market", member: "MarketReaped", required: true, citation: "02 §5; 02 §6" },
  { id: "event.market.revenue_swept", compatGroup: "event", pallet: "Market", member: "RevenueSwept", required: true, citation: "02 §5; 02 §6" },
  { id: "event.market.traded", compatGroup: "event", pallet: "Market", member: "Traded", required: true, citation: "02 §5; 02 §6" },
  { id: "event.oracle.adjudicated", compatGroup: "event", pallet: "Oracle", member: "Adjudicated", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.adjudication_requested", compatGroup: "event", pallet: "Oracle", member: "AdjudicationRequested", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.challenged", compatGroup: "event", pallet: "Oracle", member: "Challenged", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.component_settled", compatGroup: "event", pallet: "Oracle", member: "ComponentSettled", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.neutral_settlement", compatGroup: "event", pallet: "Oracle", member: "NeutralSettlement", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.quorum_failed", compatGroup: "event", pallet: "Oracle", member: "QuorumFailed", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.recompute_proven", compatGroup: "event", pallet: "Oracle", member: "RecomputeProven", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.reported", compatGroup: "event", pallet: "Oracle", member: "Reported", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.reporter_ejected", compatGroup: "event", pallet: "Oracle", member: "ReporterEjected", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.reporter_registered", compatGroup: "event", pallet: "Oracle", member: "ReporterRegistered", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.reporter_slashed", compatGroup: "event", pallet: "Oracle", member: "ReporterSlashed", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.reserve_probe_result", compatGroup: "event", pallet: "Oracle", member: "ReserveProbeResult", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.reserve_probe_sent", compatGroup: "event", pallet: "Oracle", member: "ReserveProbeSent", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.reserve_recovered", compatGroup: "event", pallet: "Oracle", member: "ReserveRecovered", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.reserve_unhealthy", compatGroup: "event", pallet: "Oracle", member: "ReserveUnhealthy", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.retention_expired", compatGroup: "event", pallet: "Oracle", member: "RetentionExpired", required: true, citation: "02 §6; 02 §7.2; 07 §11(1)" },
  { id: "event.oracle.round_escalated", compatGroup: "event", pallet: "Oracle", member: "RoundEscalated", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.watchtower_inactive", compatGroup: "event", pallet: "Oracle", member: "WatchtowerInactive", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.watchtower_registered", compatGroup: "event", pallet: "Oracle", member: "WatchtowerRegistered", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.watchtower_slashed", compatGroup: "event", pallet: "Oracle", member: "WatchtowerSlashed", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.window_acknowledged", compatGroup: "event", pallet: "Oracle", member: "WindowAcknowledged", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.oracle.window_extended", compatGroup: "event", pallet: "Oracle", member: "WindowExtended", required: true, citation: "02 §6; 02 §7.2" },
  { id: "event.question_service.question_registered", compatGroup: "event", pallet: "QuestionService", member: "QuestionRegistered", required: true, citation: "02 §4a; 02 §6" },
  { id: "event.question_service.question_sealed", compatGroup: "event", pallet: "QuestionService", member: "QuestionSealed", required: true, citation: "02 §4a; 02 §6" },
  { id: "event.question_service.question_settled", compatGroup: "event", pallet: "QuestionService", member: "QuestionSettled", required: true, citation: "02 §4a; 02 §6" },
  { id: "event.question_service.question_voided", compatGroup: "event", pallet: "QuestionService", member: "QuestionVoided", required: true, citation: "02 §4a; 02 §6" },
  { id: "event.registry.epoch_closed.incident", compatGroup: "event", pallet: "IncidentRegistry", member: "RegistryEpochClosed", required: true, citation: "02 §6" },
  { id: "event.registry.epoch_closed.milestone", compatGroup: "event", pallet: "MilestoneRegistry", member: "RegistryEpochClosed", required: true, citation: "02 §6" },
  { id: "event.registry.filing_bond_slashed.incident", compatGroup: "event", pallet: "IncidentRegistry", member: "FilingBondSlashed", required: true, citation: "02 §6" },
  { id: "event.registry.filing_bond_slashed.milestone", compatGroup: "event", pallet: "MilestoneRegistry", member: "FilingBondSlashed", required: true, citation: "02 §6" },
  { id: "event.registry.incident_challenged", compatGroup: "event", pallet: "IncidentRegistry", member: "IncidentChallenged", required: true, citation: "02 §6" },
  { id: "event.registry.incident_filed", compatGroup: "event", pallet: "IncidentRegistry", member: "IncidentFiled", required: true, citation: "02 §6" },
  { id: "event.registry.incident_rejected", compatGroup: "event", pallet: "IncidentRegistry", member: "IncidentRejected", required: true, citation: "02 §6" },
  { id: "event.registry.incident_upheld", compatGroup: "event", pallet: "IncidentRegistry", member: "IncidentUpheld", required: true, citation: "02 §6" },
  { id: "event.registry.milestone_accepted", compatGroup: "event", pallet: "MilestoneRegistry", member: "MilestoneAccepted", required: true, citation: "02 §6" },
  { id: "event.registry.milestone_challenged", compatGroup: "event", pallet: "MilestoneRegistry", member: "MilestoneChallenged", required: true, citation: "02 §6" },
  { id: "event.registry.milestone_filed", compatGroup: "event", pallet: "MilestoneRegistry", member: "MilestoneFiled", required: true, citation: "02 §6" },
  { id: "event.registry.milestone_rejected", compatGroup: "event", pallet: "MilestoneRegistry", member: "MilestoneRejected", required: true, citation: "02 §6" },
  { id: "event.registry.window_acknowledged.incident", compatGroup: "event", pallet: "IncidentRegistry", member: "WindowAcknowledged", required: true, citation: "02 §6" },
  { id: "event.registry.window_acknowledged.milestone", compatGroup: "event", pallet: "MilestoneRegistry", member: "WindowAcknowledged", required: true, citation: "02 §6" },
  { id: "event.registry.window_extended.incident", compatGroup: "event", pallet: "IncidentRegistry", member: "WindowExtended", required: true, citation: "02 §6" },
  { id: "event.registry.window_extended.milestone", compatGroup: "event", pallet: "MilestoneRegistry", member: "WindowExtended", required: true, citation: "02 §6" },
  { id: "event.system.code_updated", compatGroup: "event", pallet: "System", member: "CodeUpdated", required: true, citation: "02 §6" },
  { id: "event.system.upgrade_authorized", compatGroup: "event", pallet: "System", member: "UpgradeAuthorized", required: true, citation: "02 §6" },
  { id: "storage.attestor.attestations", compatGroup: "query", pallet: "Attestor", member: "Attestations", required: true, citation: "02 §7.5" },
  { id: "storage.attestor.liabilities", compatGroup: "query", pallet: "Attestor", member: "Liabilities", required: true, citation: "02 §7.5" },
  { id: "storage.attestor.members", compatGroup: "query", pallet: "Attestor", member: "Members", required: true, citation: "02 §7.5" },
  { id: "storage.attestor.next_attestation_id", compatGroup: "query", pallet: "Attestor", member: "NextAttestationId", required: true, citation: "02 §7.5" },
  { id: "storage.attestor.revocations", compatGroup: "query", pallet: "Attestor", member: "Revocations", required: true, citation: "02 §7.5" },
  { id: "storage.client_registry.clients", compatGroup: "query", pallet: "ClientRegistry", member: "Clients", required: true, citation: "02 §4a; 02 §7" },
  { id: "storage.constitution.params", compatGroup: "query", pallet: "Constitution", member: "Params", required: true, citation: "02 §7.3" },
  { id: "storage.constitution.phase_flags", compatGroup: "query", pallet: "Constitution", member: "PhaseFlags", required: true, citation: "02 §7.3" },
  { id: "storage.epoch.cohorts", compatGroup: "query", pallet: "Epoch", member: "Cohorts", required: true, citation: "02 §7.1" },
  { id: "storage.epoch.epoch_of", compatGroup: "query", pallet: "Epoch", member: "EpochOf", required: true, citation: "02 §7.1" },
  { id: "storage.epoch.intake_queue", compatGroup: "query", pallet: "Epoch", member: "IntakeQueue", required: true, citation: "02 §7.1" },
  { id: "storage.epoch.proposals", compatGroup: "query", pallet: "Epoch", member: "Proposals", required: true, citation: "02 §7.1" },
  { id: "storage.epoch.recent_cohort_summaries", compatGroup: "query", pallet: "Epoch", member: "RecentCohortSummaries", required: true, citation: "02 §7.1" },
  { id: "storage.execution_guard.execution_records", compatGroup: "query", pallet: "ExecutionGuard", member: "ExecutionRecords", required: true, citation: "02 §7.4" },
  { id: "storage.execution_guard.queue", compatGroup: "query", pallet: "ExecutionGuard", member: "Queue", required: true, citation: "02 §7.4" },
  { id: "storage.execution_guard.ratifications", compatGroup: "query", pallet: "ExecutionGuard", member: "Ratifications", required: true, citation: "02 §7.4" },
  { id: "storage.foreign_assets.account", compatGroup: "query", pallet: "ForeignAssets", member: "Account", required: true, citation: "02 §7.4; 02 §8" },
  { id: "storage.guardian.allowances", compatGroup: "query", pallet: "Guardian", member: "Allowances", required: true, citation: "02 §7.4 guardian allowances" },
  { id: "storage.guardian.members", compatGroup: "query", pallet: "Guardian", member: "Members", required: true, citation: "02 §7.4 guardian membership" },
  { id: "storage.identity.parachain_id", compatGroup: "query", pallet: "ParachainInfo", member: "ParachainId", required: true, citation: "02 §8" },
  { id: "storage.identity.usdc_asset", compatGroup: "query", pallet: "ForeignAssets", member: "Asset", required: true, citation: "02 §8" },
  { id: "storage.identity.usdc_metadata", compatGroup: "query", pallet: "ForeignAssets", member: "Metadata", required: true, citation: "02 §8" },
  { id: "storage.ledger.baseline_vaults", compatGroup: "query", pallet: "ConditionalLedger", member: "BaselineVaults", required: true, citation: "02 §7.4" },
  { id: "storage.ledger.position_totals", compatGroup: "query", pallet: "ConditionalLedger", member: "PositionTotals", required: true, citation: "02 §7.4" },
  { id: "storage.ledger.positions", compatGroup: "query", pallet: "ConditionalLedger", member: "Positions", required: true, citation: "02 §7.4" },
  { id: "storage.ledger.vaults", compatGroup: "query", pallet: "ConditionalLedger", member: "Vaults", required: true, citation: "02 §7.4" },
  { id: "storage.market.baseline_market_of", compatGroup: "query", pallet: "Market", member: "BaselineMarketOf", required: true, citation: "02 §7.4" },
  { id: "storage.market.markets", compatGroup: "query", pallet: "Market", member: "Markets", required: true, citation: "02 §7.4" },
  { id: "storage.oracle.component_values", compatGroup: "query", pallet: "Oracle", member: "ComponentValues", required: true, citation: "02 §7.2" },
  { id: "storage.oracle.reporters", compatGroup: "query", pallet: "Oracle", member: "Reporters", required: true, citation: "02 §7.2" },
  { id: "storage.oracle.reserve_health", compatGroup: "query", pallet: "Oracle", member: "ReserveHealth", required: true, citation: "02 §7.2" },
  { id: "storage.oracle.rounds", compatGroup: "query", pallet: "Oracle", member: "Rounds", required: true, citation: "02 §7.2" },
  { id: "storage.oracle.watchtowers", compatGroup: "query", pallet: "Oracle", member: "Watchtowers", required: true, citation: "02 §7.2" },
  { id: "storage.question_service.questions", compatGroup: "query", pallet: "QuestionService", member: "Questions", required: true, citation: "02 §4a; 02 §7" },
  { id: "storage.question_service.reports", compatGroup: "query", pallet: "QuestionService", member: "Reports", required: true, citation: "02 §4a; 02 §7" },
  { id: "storage.service_ledger.baseline_vaults", compatGroup: "query", pallet: "ServiceLedger", member: "BaselineVaults", required: true, citation: "02 §7.1; 02 §7.4" },
  { id: "storage.service_ledger.position_totals", compatGroup: "query", pallet: "ServiceLedger", member: "PositionTotals", required: true, citation: "02 §7.1; 02 §7.4" },
  { id: "storage.service_ledger.positions", compatGroup: "query", pallet: "ServiceLedger", member: "Positions", required: true, citation: "02 §7.1; 02 §7.4" },
  { id: "storage.service_ledger.vaults", compatGroup: "query", pallet: "ServiceLedger", member: "Vaults", required: true, citation: "02 §7.1; 02 §7.4" },
  { id: "storage.system.account", compatGroup: "query", pallet: "System", member: "Account", required: true, citation: "02 §7.4" },
  { id: "storage.welfare.gate_breach_flags", compatGroup: "query", pallet: "Welfare", member: "GateBreachFlags", required: true, citation: "02 §7.4" },
  { id: "storage.welfare.metric_specs", compatGroup: "query", pallet: "Welfare", member: "MetricSpecs", required: true, citation: "02 §7.4" },
  { id: "storage.welfare.snapshots", compatGroup: "query", pallet: "Welfare", member: "Snapshots", required: true, citation: "02 §7.4" },
];
